[package]
name = "mar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mar"
path = "src/bin/main.rs"

[dependencies]
clap = "4.3.23"
eval = "0.4.3"
# full_moon = { version = "0.18.1", features = ["lua54"] }
glob = "0.3.1"
regex = "1.9.3"
